base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *base
  database: amazon_scraper_development
  socket: /tmp/mysql.sock

test:
  <<: *base
  database: amazon_scraper_test
  socket: /tmp/mysql.sock

production:
  <<: *base
  database: amazon_scraper_production
  socket: /tmp/mysql.sock