# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1bf2251ca0c558431658ac15bded73e0f6ec339d1b38a7db545c19479b4a78642e5ae24537e386c695d521652589a674721365d0a5a1873fc539da1f9c3bf9

test:
  secret_key_base: d25a9bbb985df35ada9baf5b890a3d157e379006038c5f8b7565097ec8d8769898bf66d40e3ecca5fe692fe28aeff1d9d1b921c61a082500976ceb109847ff25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
